<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SecRolePrivSeeder extends Seeder
{
	public function run()
	{
		$data = [
			[
				'role_id'		=> 1,
				'module_id'		=> 1,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 2,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 3,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 4,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 5,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 6,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 7,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 8,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 9,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 1,
				'module_id'		=> 10,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 1,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 2,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 0,
				'allow_print'	=> 1,
				'allow_approve'	=> 0,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 3,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 0,
				'allow_print'	=> 1,
				'allow_approve'	=> 0,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 4,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 0,
				'allow_print'	=> 1,
				'allow_approve'	=> 0,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 6,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 0,
				'allow_print'	=> 1,
				'allow_approve'	=> 0,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 7,
				'allow_view'	=> 1,
				'allow_new'		=> 0,
				'allow_edit'	=> 0,
				'allow_delete'	=> 0,
				'allow_print'	=> 0,
				'allow_approve'	=> 0,
			],
			[
				'role_id'		=> 2,
				'module_id'		=> 10,
				'allow_view'	=> 1,
				'allow_new'		=> 1,
				'allow_edit'	=> 1,
				'allow_delete'	=> 1,
				'allow_print'	=> 1,
				'allow_approve'	=> 1,
			],
			[
				'role_id'		=> 3,
				'module_id'		=> 1,
				'allow_view'	=> 1,
				'allow_new'		=> 0,
				'allow_edit'	=> 0,
				'allow_delete'	=> 0,
				'allow_print'	=> 1,
				'allow_approve'	=> 0,
			],
		];

		$this->db->table('sec_role_priv')->insertBatch($data);
	}
}
